#!/bin/bash

cat 0 | wc -l && sort -u -o 0 0 && cat 0 | wc -l
cat 1 | wc -l && sort -u -o 1 1 && cat 1 | wc -l
cat 2 | wc -l && sort -u -o 2 2 && cat 2 | wc -l
cat 3 | wc -l && sort -u -o 3 3 && cat 3 | wc -l
cat 4 | wc -l && sort -u -o 4 4 && cat 4 | wc -l
cat 5 | wc -l && sort -u -o 5 5 && cat 5 | wc -l
cat 6 | wc -l && sort -u -o 6 6 && cat 6 | wc -l
cat 7 | wc -l && sort -u -o 7 7 && cat 7 | wc -l
cat 8 | wc -l && sort -u -o 8 8 && cat 8 | wc -l
cat 9 | wc -l && sort -u -o 9 9 && cat 9 | wc -l
cat a | wc -l && sort -u -o a a && cat a | wc -l
cat b | wc -l && sort -u -o b b && cat b | wc -l
cat c | wc -l && sort -u -o c c && cat c | wc -l
cat d | wc -l && sort -u -o d d && cat d | wc -l
cat e | wc -l && sort -u -o e e && cat e | wc -l
cat f | wc -l && sort -u -o f f && cat f | wc -l
cat g | wc -l && sort -u -o g g && cat g | wc -l
cat h | wc -l && sort -u -o h h && cat h | wc -l
cat i | wc -l && sort -u -o i i && cat i | wc -l
cat j | wc -l && sort -u -o j j && cat j | wc -l
cat k | wc -l && sort -u -o k k && cat k | wc -l
cat l | wc -l && sort -u -o l l && cat l | wc -l
cat m | wc -l && sort -u -o m m && cat m | wc -l
cat n | wc -l && sort -u -o n n && cat n | wc -l
cat o | wc -l && sort -u -o o o && cat o | wc -l
cat p | wc -l && sort -u -o p p && cat p | wc -l
cat q | wc -l && sort -u -o q q && cat q | wc -l
cat r | wc -l && sort -u -o r r && cat r | wc -l
cat s | wc -l && sort -u -o s s && cat s | wc -l
cat t | wc -l && sort -u -o t t && cat t | wc -l
cat u | wc -l && sort -u -o u u && cat u | wc -l
cat v | wc -l && sort -u -o v v && cat v | wc -l
cat w | wc -l && sort -u -o w w && cat w | wc -l
cat w0 | wc -l && sort -u -o w0 w0 && cat w0 | wc -l
cat w1 | wc -l && sort -u -o w1 w1 && cat w1 | wc -l
cat w2 | wc -l && sort -u -o w2 w2 && cat w2 | wc -l
cat w3 | wc -l && sort -u -o w3 w3 && cat w3 | wc -l
cat w4 | wc -l && sort -u -o w4 w4 && cat w4 | wc -l
cat w5 | wc -l && sort -u -o w5 w5 && cat w5 | wc -l
cat w6 | wc -l && sort -u -o w6 w6 && cat w6 | wc -l
cat w7 | wc -l && sort -u -o w7 w7 && cat w7 | wc -l
cat w8 | wc -l && sort -u -o w8 w8 && cat w8 | wc -l
cat w9 | wc -l && sort -u -o w9 w9 && cat w9 | wc -l
cat wa | wc -l && sort -u -o wa wa && cat wa | wc -l
cat wb | wc -l && sort -u -o wb wb && cat wb | wc -l
cat wc | wc -l && sort -u -o wc wc && cat wc | wc -l
cat wd | wc -l && sort -u -o wd wd && cat wd | wc -l
cat we | wc -l && sort -u -o we we && cat we | wc -l
cat wf | wc -l && sort -u -o wf wf && cat wf | wc -l
cat wg | wc -l && sort -u -o wg wg && cat wg | wc -l
cat wh | wc -l && sort -u -o wh wh && cat wh | wc -l
cat wi | wc -l && sort -u -o wi wi && cat wi | wc -l
cat wj | wc -l && sort -u -o wj wj && cat wj | wc -l
cat wk | wc -l && sort -u -o wk wk && cat wk | wc -l
cat wl | wc -l && sort -u -o wl wl && cat wl | wc -l
cat wm | wc -l && sort -u -o wm wm && cat wm | wc -l
cat wn | wc -l && sort -u -o wn wn && cat wn | wc -l
cat wo | wc -l && sort -u -o wo wo && cat wo | wc -l
cat wp | wc -l && sort -u -o wp wp && cat wp | wc -l
cat wq | wc -l && sort -u -o wq wq && cat wq | wc -l
cat wr | wc -l && sort -u -o wr wr && cat wr | wc -l
cat ws | wc -l && sort -u -o ws ws && cat ws | wc -l
cat wt | wc -l && sort -u -o wt wt && cat wt | wc -l
cat wu | wc -l && sort -u -o wu wu && cat wu | wc -l
cat wv | wc -l && sort -u -o wv wv && cat wv | wc -l
cat ww | wc -l && sort -u -o ww ww && cat ww | wc -l
cat wx | wc -l && sort -u -o wx wx && cat wx | wc -l
cat wy | wc -l && sort -u -o wy wy && cat wy | wc -l
cat wz | wc -l && sort -u -o wz wz && cat wz | wc -l
cat x | wc -l && sort -u -o x x && cat x | wc -l
cat y | wc -l && sort -u -o y y && cat y | wc -l
cat z | wc -l && sort -u -o z z && cat z | wc -l

