#!/bin/bash

#Script to filter out whitelist domains
grep -Fvf wl.txt 0 > 0.new && rm -rf 0 && mv 0.new 0
grep -Fvf wl.txt 0-w > 0-w.new && rm -rf 0-w && mv 0-w.new 0-w
grep -Fvf wl.txt 1 > 1.new && rm -rf 1 && mv 1.new 1
grep -Fvf wl.txt 1-w > 1-w.new && rm -rf 1-w && mv 1-w.new 1-w
grep -Fvf wl.txt 2 > 2.new && rm -rf 2 && mv 2.new 2
grep -Fvf wl.txt 2-w > 2-w.new && rm -rf 2-w && mv 2-w.new 2-w
grep -Fvf wl.txt 3 > 3.new && rm -rf 3 && mv 3.new 3
grep -Fvf wl.txt 3-w > 3-w.new && rm -rf 3-w && mv 3-w.new 3-w
grep -Fvf wl.txt 4 > 4.new && rm -rf 4 && mv 4.new 4
grep -Fvf wl.txt 4-w > 4-w.new && rm -rf 4-w && mv 4-w.new 4-w
grep -Fvf wl.txt 5 > 5.new && rm -rf 5 && mv 5.new 5
grep -Fvf wl.txt 5-w > 5-w.new && rm -rf 5-w && mv 5-w.new 5-w
grep -Fvf wl.txt 6 > 6.new && rm -rf 6 && mv 6.new 6
grep -Fvf wl.txt 6-w > 6-w.new && rm -rf 6-w && mv 6-w.new 6-w
grep -Fvf wl.txt 7 > 7.new && rm -rf 7 && mv 7.new 7
grep -Fvf wl.txt 7-w > 7-w.new && rm -rf 7-w && mv 7-w.new 7-w
grep -Fvf wl.txt 8 > 8.new && rm -rf 8 && mv 8.new 8
grep -Fvf wl.txt 8-w > 8-w.new && rm -rf 8-w && mv 8-w.new 8-w
grep -Fvf wl.txt 9 > 9.new && rm -rf 9 && mv 9.new 9
grep -Fvf wl.txt 9-w > 9-w.new && rm -rf 9-w && mv 9-w.new 9-w
grep -Fvf wl.txt a > a.new && rm -rf a && mv a.new a
grep -Fvf wl.txt a-w > a-w.new && rm -rf a-w && mv a-w.new a-w
grep -Fvf wl.txt b > b.new && rm -rf b && mv b.new b
grep -Fvf wl.txt b-w > b-w.new && rm -rf b-w && mv b-w.new b-w
grep -Fvf wl.txt c > c.new && rm -rf c && mv c.new c
grep -Fvf wl.txt c-w > c-w.new && rm -rf c-w && mv c-w.new c-w
grep -Fvf wl.txt d > d.new && rm -rf d && mv d.new d
grep -Fvf wl.txt d-w > d-w.new && rm -rf d-w && mv d-w.new d-w
grep -Fvf wl.txt e > e.new && rm -rf e && mv e.new e
grep -Fvf wl.txt e-w > e-w.new && rm -rf e-w && mv e-w.new e-w
grep -Fvf wl.txt f > f.new && rm -rf f && mv f.new f
grep -Fvf wl.txt f-w > f-w.new && rm -rf f-w && mv f-w.new f-w
grep -Fvf wl.txt g > g.new && rm -rf g && mv g.new g
grep -Fvf wl.txt g-w > g-w.new && rm -rf g-w && mv g-w.new g-w
grep -Fvf wl.txt h > h.new && rm -rf h && mv h.new h
grep -Fvf wl.txt h-w > h-w.new && rm -rf h-w && mv h-w.new h-w
grep -Fvf wl.txt i > i.new && rm -rf i && mv i.new i
grep -Fvf wl.txt i-w > i-w.new && rm -rf i-w && mv i-w.new i-w
grep -Fvf wl.txt j > j.new && rm -rf j && mv j.new j
grep -Fvf wl.txt j-w > j-w.new && rm -rf j-w && mv j-w.new j-w
grep -Fvf wl.txt k > k.new && rm -rf k && mv k.new k
grep -Fvf wl.txt k-w > k-w.new && rm -rf k-w && mv k-w.new k-w
grep -Fvf wl.txt l > l.new && rm -rf l && mv l.new l
grep -Fvf wl.txt l-w > l-w.new && rm -rf l-w && mv l-w.new l-w
grep -Fvf wl.txt m > m.new && rm -rf m && mv m.new m
grep -Fvf wl.txt m-w > m-w.new && rm -rf m-w && mv m-w.new m-w
grep -Fvf wl.txt n > n.new && rm -rf n && mv n.new n
grep -Fvf wl.txt n-w > n-w.new && rm -rf n-w && mv n-w.new n-w
grep -Fvf wl.txt o > o.new && rm -rf o && mv o.new o
grep -Fvf wl.txt o-w > o-w.new && rm -rf o-w && mv o-w.new o-w
grep -Fvf wl.txt p > p.new && rm -rf p && mv p.new p
grep -Fvf wl.txt p-w > p-w.new && rm -rf p-w && mv p-w.new p-w
grep -Fvf wl.txt q > q.new && rm -rf q && mv q.new q
grep -Fvf wl.txt q-w > q-w.new && rm -rf q-w && mv q-w.new q-w
grep -Fvf wl.txt r > r.new && rm -rf r && mv r.new r
grep -Fvf wl.txt r-w > r-w.new && rm -rf r-w && mv r-w.new r-w
grep -Fvf wl.txt s > s.new && rm -rf s && mv s.new s
grep -Fvf wl.txt s-w > s-w.new && rm -rf s-w && mv s-w.new s-w
grep -Fvf wl.txt t > t.new && rm -rf t && mv t.new t
grep -Fvf wl.txt t-w > t-w.new && rm -rf t-w && mv t-w.new t-w
grep -Fvf wl.txt u > u.new && rm -rf u && mv u.new u
grep -Fvf wl.txt u-w > u-w.new && rm -rf u-w && mv u-w.new u-w
grep -Fvf wl.txt v > v.new && rm -rf v && mv v.new v
grep -Fvf wl.txt v-w > v-w.new && rm -rf v-w && mv v-w.new v-w
grep -Fvf wl.txt w > w.new && rm -rf w && mv w.new w
grep -Fvf wl.txt w-w > w-w.new && rm -rf w-w && mv w-w.new w-w
grep -Fvf wl.txt x > x.new && rm -rf x && mv x.new x
grep -Fvf wl.txt x-w > x-w.new && rm -rf x-w && mv x-w.new x-w
grep -Fvf wl.txt y > y.new && rm -rf y && mv y.new y
grep -Fvf wl.txt y-w > y-w.new && rm -rf y-w && mv y-w.new y-w
grep -Fvf wl.txt z > z.new && rm -rf z && mv z.new z
grep -Fvf wl.txt z-w > z-w.new && rm -rf z-w && mv z-w.new z-w
